pipeline:
  name: riceBuilder
  identifier: riceBuilder
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: setup.sh
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
